server:
  port: 8081
  servlet:
    context-path: /room

spring:
  application:
    name: room-service

  datasource:
    url: jdbc:mysql://localhost:3306/room_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver   # ✅ sửa chỗ này

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect   # ✅ THÊM DÒNG NÀY

app:
  services:
    identity: http://localhost:8080/identity
idp:
  url: http://localhost:8180
  client-id: HotelContinentalBackend
  client-secret: 0NnN2ZKjioAFkWuRyjgP0JLE5F8crVFz
cloudinary:
  cloud-name: dweslsemq
  api-key: 489933971286769
  api-secret: KKuSOQMLU7W-Nl3eJXx-qs9Mb9E
  folder: hotelcontinental_rooms