server:
  port: 8085
  servlet:
    context-path: /billing

spring:
  application:
    name: billing-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/HotelContinental

  datasource:
    url: jdbc:mysql://localhost:3306/billing_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  services:
    identity: http://localhost:8080/identity
    booking: http://localhost:8082/booking
    catalog: http://localhost:8083/catalog

idp:
  url: http://localhost:8180
  client-id: HotelContinentalBackend
  client-secret: 0NnN2ZKjioAFkWuRyjgP0JLE5F8crVFz
